frontend:
  image:
    repository: ghcr.io/kkamji98/play-hub-frontend
    tag: e939d243ce5d0fb5a85e772e9008d81ce31cbd42 # frontend-tag
    pullPolicy: IfNotPresent
  containerPort: 8080
  replicas: 1
  service:
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

backend:
  image:
    repository: ghcr.io/kkamji98/play-hub-backend
    tag: e939d243ce5d0fb5a85e772e9008d81ce31cbd42 # backend-tag
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 8080
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  className: nginx
  host: play-hub.kkamji.net
  tls:
    enabled: true
    clusterIssuer: letsencrypt-prod
  annotations:
    external-dns.alpha.kubernetes.io/target: "121.130.214.237"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
