frontend:
  image:
    repository: ghcr.io/kkamji/play-hub-frontend
    tag: latest # frontend-tag
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

backend:
  image:
    repository: ghcr.io/kkamji/play-hub-backend
    tag: latest # backend-tag
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 8080
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  className: nginx
  host: play-hub.kkamji.net
  tls:
    enabled: true
    clusterIssuer: letsencrypt-prod
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
