apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "play-hub.fullname" . }}-backend
  labels:
    {{- include "play-hub.labels" . | nindent 4 }}
    {{- include "play-hub.backend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "play-hub.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "play-hub.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
